import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

/**
 * Insights — the evidence file. One markdown file per entry, loaded through the
 * content layer so the index and the article route read from the same source.
 *
 * Everything published here is either a measured result from a real account or
 * an argument built on one. There is no opinion tier: if an entry cannot point
 * at a number and say where the number came from, it does not go up.
 */
const insights = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/insights' }),
  schema: z.object({
    /** Shown as the article <h1> and, suffixed, as the page title. Keep under ~60 chars. */
    title: z.string(),
    /** The lede under the article header. Free to run long — it is read on the
     *  page, where there is room for it. */
    description: z.string(),
    /** The <meta name="description">. Optional: falls back to `description`.
     *  Exists because a good on-page lede and a good SERP snippet are different
     *  lengths — Google truncates around 155–160 characters, and every entry's
     *  lede ran past that. */
    metaDescription: z.string().max(160).optional(),
    date: z.coerce.date(),
    updated: z.coerce.date().optional(),
    tags: z.array(z.string()),
    /** Whole minutes. Written by hand so it stays honest. */
    readingTime: z.number(),
    draft: z.boolean().default(false),
    /** Single word or short phrase. Drives the index column and the topic list. */
    category: z.string(),

    /* ---- Evidence metadata -------------------------------------------------
       The index sorts and labels on these. They exist so a reader can tell, at
       a glance and before clicking, whether they are about to read a result or
       a reading of a result. */

    /** What sort of entry this is. Case studies carry an account's own numbers. */
    kind: z.enum(['Case study', 'Report', 'Article']),
    /** One line naming the account or dataset the entry draws on. Required, so
     *  no entry can quietly float free of a source. */
    source: z.string(),
    /** The single figure the index puts in front of the entry, e.g. '3.99×'. */
    headline: z.string().optional(),
    /** What that figure measures, e.g. 'cheaper per usable piece'. */
    headlineLabel: z.string().optional(),
    /** Pins one entry to the top of the index regardless of date. */
    featured: z.boolean().default(false),

    /** Cover art, served from /public. Currently placeholders generated by
     *  scripts/build-covers.py; swapping in a real photograph is a change to
     *  this line and nothing else.
     *
     *  Deliberately NOT wired into the og:image tag while these are SVG —
     *  Facebook, X and LinkedIn all reject SVG for share cards, so the pages
     *  fall back to SITE.ogImage. Point Base's `image` prop at this field once
     *  the real covers land as PNG or JPG. */
    cover: z.string(),
    /** What the cover shows, for a reader who cannot see it. Never a repeat of
     *  the title — a screen reader already has that from the heading. */
    coverAlt: z.string(),
  }),
});

export const collections = { insights };
